web:
  container_name: cid10_api_web
  build: .
  image: datagenno/cid10-api
  volumes:
    - .:/var/www/html
  ports:
    - "8080:80"
  links:
    - elasticsearch
  environment:
    - ENV='DEVELOPMENT'
    - ELASTIC_SEARCH_HOSTNAME=${ELASTIC_SEARCH_HOSTNAME}
    - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    - BASIC_AUTHENTICATION_USERNAME=${BASIC_AUTHENTICATION_USERNAME}
    - BASIC_AUTHENTICATION_PASSWORD=${BASIC_AUTHENTICATION_PASSWORD}


elasticsearch:
  image: library/elasticsearch
  container_name: cid10_api_elasticsearch
  ports:
    - "9200:9200"
